version: "3.5"

services:
  processing:
    build: './processing'
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  pre_processing:
    build: './pre_processing'
    ports:
      - "8084:8084"
  telebot:
    build: './telebot'


