version: "3.5"

services:
  processing:
    build: './processing'
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  pre_processing:
    build: './pre_processing'
    ports:
      - "8084:8084"
  telebot:
    build: './telebot'
    depends_on:
      - "pre_processing"
      - "processing"
  spellchecking_en:
    image: "deeppavlov/base-gpu:latest"
    ports:
      - "8082:5000"
    volumes:
      - "data_en:/root/.deeppavlov"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CONFIG=brillmoore_wikitypos_en
  spellchecking_ru:
    image: "deeppavlov/base-gpu:latest"
    ports:
      - "8081:5000"
    volumes:
      - "data_ru:/root/.deeppavlov"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CONFIG=levenshtein_corrector_ru
  spellchecking:
    build: './post_processing'
    ports:
      - "8083:8083"

volumes:
  data_en:
  data_ru:



